server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.111.128:3306/test?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456

#必须配置，Mybatis才能通过配置找到Mapper.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
